spring:
  application:
    name: auth-service

  datasource:
    password: vijay
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

server:
  port: 9898