spring:
  application:
    name: inventory-service
  datasource:
    password: vijay
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9092

# jwt:secret: 99abf4f1ff5a1f59e20ec1f99a88af7b7e9c14b072c9a2533634cb47c1a14c3a